version: '3.8'

volumes:
  static:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './static'
  media:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './media'
  nginx_templates:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './nginx_templates'
  postgres_db:

services:
  db:
    image: postgres:12.4
    container_name: postgres_foodgram
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    env_file:
      - ./.env
  foodgram:
    image: sovushkasever/foodgram:latest
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    restart: always
    image: nginx:1.19
    container_name: webserver_foodgram
    volumes:
      - static:/usr/share/nginx/html/static/
      - nginx_templates:/etc/nginx/templates
      - media:/usr/share/nginx/html/media/
    ports:
      - "80:80"
    depends_on:
      - foodgram
    environment:
     - NGINX_PORT=80
     - NGINX_SERVERNAME=localhost
     - NGINX_UPSTREAM=http://foodgram:8000